AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  meeting-transcript-automator

  Sample SAM Template for meeting-transcript-automator

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  ZoomTranscriptWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/zoomTranscriptWebhookHandler
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        ZoomTranscriptWebhookApi:
          Type: Api
          Properties:
            Path: /zoom-transcript-webhook
            Method: post

Outputs:
  ZoomTranscriptWebhookApi:
    Description: API Gateway endpoint URL for Prod stage for zoom webhook function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/zoom-transcript-webhook/"
  ZoomWebhookHandlerFunction:
    Description: Webhook Lambda Function ARN
    Value: !GetAtt ZoomTranscriptWebhookFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for web hook function
    Value: !GetAtt ZoomTranscriptWebhookFunctionRole.Arn
