AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  meeting-transcript-automator

  Sample SAM Template for meeting-transcript-automator

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120

Resources:
  automationAppHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/automation-app-handler
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        automationAppHandlerApi:
          Type: Api
          Properties:
            Path: /automation-app-handler
            Method: post
      Environment: # Pass the DynamoDB table name as an environment variable
        Variables:
          DYNAMODB_TABLE_NAME: !Ref ZoomTranscriptEventDebounceTable
      Policies: # IAM policies to allow the Lambda function to access DynamoDB
        - DynamoDBCrudPolicy:
            TableName: !Ref ZoomTranscriptEventDebounceTable

  ZoomTranscriptEventDebounceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ZoomTranscriptEventDebounceTable
      AttributeDefinitions:
        - AttributeName: eventId
          AttributeType: S
      KeySchema:
        - AttributeName: eventId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  AutomationAppHandlerApi:
    Description: API Gateway endpoint URL for Prod stage for zoom webhook function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/automation-app-handler/"
  AutomationAppHandlerFunction:
    Description: Lambda Function ARN
    Value: !GetAtt AutomationAppHandlerFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for lanbda handler function
    Value: !GetAtt AutomationAppHandlerFunctionRole.Arn
  ZoomTranscriptEventDebounceTableArn:
    Description: ARN of the DynamoDB Table
    Value: !GetAtt ZoomTranscriptEventDebounceTable.Arn
